---
- name: Install Docker on GitLab-CI-Runner
  hosts: tag_gitlab-runner
  become: true

  tasks:

  - name: Add Repo key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add Repo 
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable
      state: present

  - name: Install Docker and Req
    apt:
      name: "{{ packages }}"
      update_cache: yes
    vars:
      packages:
        - apt-transport-https
        - ca-certificates 
        - curl
        - software-properties-common
        - docker-ce
        - python-pip
        - docker-compose
        