comment:
  image:
    repository: eogladkih/comment
    tag: latest
  service:
    externalPort: 9292

post:
  image:
    repository: eogladkih/post
    tag: latest
    service:
      externalPort: 5000

ui:
  image:
    repository: eogladkih/ui
    tag: latest
    service:
      externalPort: 9292
