---
- name: Install Docker and App run
  hosts: tag_docker
  become: true

  tasks:
    - name: Install Req for docker container run
      pip: 
        name: docker

    - name: Run Docker Container App
      docker_container:
        name: reddit
        image: eogladkih/otus-reddit:1.0
        ports: 
          - "9292:9292"
        state: started

